# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff071e841fa2af2b4b493f751520de2854e6c9abac166cc601d2c7a878da1dee9fa11f16743121433113db459fd21de392c0a830e9fcb9ddb17e7f7b6f26975e

test:
  secret_key_base: 693f401931c865d7c5e1b7e49d37dd06ee52e6a8d05414a3c26e1e89578a7c6c365cc560cb8dbc8f01374f2550aca13fa8e48744b72485fa19b3a334b3e13c38

# Do not keep production secrets in the repository,
# instead read values from the environment.
# YEAH RIGHT YOLO!
production:
  secret_key_base: ff071e841fa2af2b4b493f751520de2854e6c9abac166cc601d2c7a878da1dee9fa11f16743121433113db459fd21de392c0a830e9fcb9ddb17e7f7b6f26975e
